[project]
name = "hltb"
version = "0.5.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.5",
    "tabulate>=0.9.0",
]

[project.scripts]
hltb = "hltb.main:main"
